# IMS信令流程可视化分析与智能预测方案

By Marshall Zhang  
Date 2019年2月19日  
From 电力IMS信令数据

## 1.导入相关库和数据源

In [1]:
import pandas as pd
import seaborn as sea
import sklearn as sk

In [24]:
df_data = pd.read_excel("通话记录.xlsx")#数据源暂不提供

### 原始数据格式实例

In [3]:
df_data.head(10)

,主叫号码,被叫号码,开始时间,应答时间,结束时间,通话时长,源IP,目标IP,消息类型
0,8841715,18036114567,2019-01-22 19:03:07.814495,NaN,2019-01-22 19:03:08.611737,0,30.22.25.239,30.20.1.12,480
1,5337969597,8707239,2019-01-22 19:06:01.753423,2019-01-22 19:06:05.403681,2019-01-22 19:06:05.456206,1,30.20.1.12,30.20.1.80,BYE
2,8576061,8579561,2019-01-22 19:06:18.998325,NaN,NaN,0,30.22.202.4,30.20.1.80,NaN
3,8782409,17806346788,2019-01-22 19:06:03.603935,NaN,NaN,0,30.23.226.69,30.20.1.140,NaN
4,15253331888,8705270,2019-01-22 19:07:34.623272,NaN,NaN,0,30.20.1.12,30.20.1.8,NaN
5,8602862,2652380,2019-01-22 19:11:46.787491,2019-01-22 19:11:54.706545,2019-01-22 19:12:04.725882,11,30.23.100.111,30.20.200.1,BYE
6,18353261700,8637024,2019-01-22 19:11:29.326516,2019-01-22 19:11:33.72154,2019-01-22 19:11:33.76709,1,30.20.1.140,30.20.1.208,BYE
7,8667313,15966390410,2019-01-22 19:03:08.974337,NaN,NaN,0,30.23.77.7,30.20.200.3,NaN
8,8125354,8124562,2019-01-22 19:04:15.056258,NaN,2019-01-22 19:04:35.996183,0,30.21.37.132,30.20.1.8,487
9,53182424947,8462631,2019-01-22 19:04:50.735256,NaN,2019-01-22 19:05:15.517847,0,30.20.1.12,30.20.1.136,487

### 数据包含的属性

In [6]:
df_data.columns

Index(['主叫号码', '被叫号码', '开始时间', '应答时间', '结束时间', '通话时长', '源IP', '目标IP', '消息类型'], dtype='object')

### 数据总量：（呼叫总条数，属性数）

In [5]:
df_data.shape

(98400, 9)

## 2.数据清洗（删除无效、错误、缺失的数据）

In [25]:
df_data_lack_info = df_data[df_data["消息类型"].isnull()]
df_data = df_data[df_data["消息类型"].notnull()]

“消息类型”为空的数据，视为数据严重缺失的信息，做删除处理；

In [26]:
df_data_lack_info.head(5)

,主叫号码,被叫号码,开始时间,应答时间,结束时间,通话时长,源IP,目标IP,消息类型
2,8576061,8579561,2019-01-22 19:06:18.998325,NaN,NaN,0,30.22.202.4,30.20.1.80,NaN
3,8782409,17806346788,2019-01-22 19:06:03.603935,NaN,NaN,0,30.23.226.69,30.20.1.140,NaN
4,15253331888,8705270,2019-01-22 19:07:34.623272,NaN,NaN,0,30.20.1.12,30.20.1.8,NaN
7,8667313,15966390410,2019-01-22 19:03:08.974337,NaN,NaN,0,30.23.77.7,30.20.200.3,NaN
10,8566364,15205300438,2019-01-22 19:08:51.36639,NaN,NaN,0,30.23.216.21,30.20.200.1,NaN

## 3.特征工程（在原有数据基础上生成二次数据）

In [27]:
df_data["消息类型"].value_counts()

BYE    52976
487    29279
486     6580
480     1690
404      745
500      348
484       78
481       72
603       54
488       51
403       50
502        7
410        7
408        6
503        2
491        2
422        2
Name: 消息类型, dtype: int64

### 增加消息类型解释

In [31]:
df_cor = pd.read_excel("响应消息类型与原因对照表.xlsx")
df_cor.head(3)

                              消息类型  原因
0                 100 Trying 正在处理中 NaN
1                   180 Ringing 振铃 NaN
2  181 call being forwarder 呼叫正在前向 NaN

In [32]:
df_cor["原因"] = df_cor["消息类型"].apply(lambda x:x[4:])
df_cor["消息类型"] = df_cor["消息类型"].apply(lambda x:x[0:3])
df_cor.to_excel("响应消息类型与原因对照表2.xlsx")
df_cor.head()

  消息类型                           原因
0  100                 Trying 正在处理中
1  180                   Ringing 振铃
2  181  call being forwarder 呼叫正在前向
3  182                     queue 排队
4  181        session progress 会话进行

In [61]:
df_data = pd.merge(df_data,df_cor,on="消息类型",how="left")

### 增加“主叫地区”（省、市、单位/运营商）

In [ ]:
def numAnalyze(num):
    num_str = str(num)
    num_len = len(num_str)
    if num_len == 9:#全号，省外
        pass
    elif num_len == 11:#手机号/外网固话
        pass
    elif num_len ==

In [70]:
df_data["主叫长度"] = df_data["主叫号码"].apply(lambda x:len(str(x)))
df_data["被叫长度"] = df_data["被叫号码"].apply(lambda x:len(str(x)))

In [67]:
df_data["主叫长度"].value_counts()

7     80886
11     8523
10     1126
8       708
17      301
4       243
16       45
14       34
9        30
12       18
13       12
6        10
18        5
19        4
15        3
2         1
Name: 主叫长度, dtype: int64

In [71]:
df_data["被叫长度"].value_counts()

7     61264
11    26836
12     1486
8       902
10      411
3       340
1       212
2       129
9       122
6       112
4        64
17       49
16       11
13        4
19        4
14        1
18        1
15        1
Name: 被叫长度, dtype: int64

In [72]:
df_data[df_data["主叫长度"]==11]

,主叫号码,被叫号码,开始时间,应答时间,结束时间,通话时长,源IP,目标IP,消息类型,原因,主叫长度,被叫长度
3,18353261700,8637024,2019-01-22 19:11:29.326516,2019-01-22 19:11:33.72154,2019-01-22 19:11:33.76709,1,30.20.1.140,30.20.1.208,BYE,NaN,11,7
5,53182424947,8462631,2019-01-22 19:04:50.735256,NaN,2019-01-22 19:05:15.517847,0,30.20.1.12,30.20.1.136,487,request terminated 请求终止,11,7
7,13225340071,8602222,2019-01-22 19:03:11.635766,NaN,2019-01-22 19:03:11.888707,0,30.20.1.12,30.20.1.80,486,busy here 这里忙,11,7
8,13225340071,8602222,2019-01-22 19:04:55.187366,NaN,2019-01-22 19:04:55.400922,0,30.20.1.12,30.20.1.80,486,busy here 这里忙,11,7
12,13225340071,8602222,2019-01-22 19:03:39.116694,NaN,2019-01-22 19:03:39.333528,0,30.20.1.12,30.20.1.80,486,busy here 这里忙,11,7
13,17862980161,8843417,2019-01-22 19:03:52.245091,NaN,2019-01-22 19:04:31.4648,0,30.20.1.12,30.20.1.136,487,request terminated 请求终止,11,7
15,18753476111,8603281,2019-01-22 19:11:24.300103,NaN,2019-01-22 19:11:58.496059,0,30.20.1.12,30.20.1.8,487,request terminated 请求终止,11,7
18,17753048393,8565354,2019-01-22 19:03:38.234313,NaN,2019-01-22 19:04:17.30807,0,30.20.1.140,30.20.1.136,487,request terminated 请求终止,11,7
26,13225340071,8602222,2019-01-22 19:03:56.205386,NaN,2019-01-22 19:03:56.424524,0,30.20.1.12,30.20.1.80,486,busy here 这里忙,11,7
30,13225340071,8602222,2019-01-22 19:04:17.924758,NaN,2019-01-22 19:04:18.111936,0,30.20.1.12,30.20.1.80,486,busy here 这里忙,11,7
33,18753476111,8603280,2019-01-22 19:04:18.18851,NaN,2019-01-22 19:04:18.24975,0,30.20.1.12,30.20.1.6,404,not found 未发现,11,7
37,18206599370,8662260,2019-01-22 19:06:00.5173,2019-01-22 19:06:04.2829,2019-01-22 19:06:04.331922,1,30.20.1.12,30.20.1.80,BYE,NaN,11,7
40,15621127969,8841621,2019-01-22 19:10:09.20084,NaN,2019-01-22 19:10:32.80368,0,30.20.1.12,30.20.1.136,487,request terminated 请求终止,11,7
52,13606460883,8637769,2019-01-22 19:10:00.799003,NaN,2019-01-22 19:10:25.411091,0,30.20.1.140,30.20.1.8,487,request terminated 请求终止,11,7
62,13225340071,8602222,2019-01-22 19:05:17.748339,NaN,2019-01-22 19:05:17.957133,0,30.20.1.12,30.20.1.80,486,busy here 这里忙,11,7
65,18353068068,8567337,2019-01-22 19:11:22.893726,2019-01-22 19:11:49.592255,2019-01-22 19:11:49.629758,1,30.20.1.140,30.20.1.80,BYE,NaN,11,7
70,18363992545,8842000,2019-01-22 19:11:25.776115,NaN,2019-01-22 19:12:11.146233,0,30.20.1.12,30.20.1.136,487,request terminated 请求终止,11,7
77,13405404188,8567830,2019-01-22 19:10:06.175257,NaN,2019-01-22 19:10:06.339603,0,30.20.1.140,30.20.1.80,486,busy here 这里忙,11,7
78,13053878189,8567999,2019-01-22 19:11:13.470076,2019-01-22 19:11:17.631516,2019-01-22 19:11:17.680023,1,30.20.1.140,30.20.1.80,BYE,NaN,11,7
80,17553011774,8566326,2019-01-22 19:10:05.163901,2019-01-22 19:10:11.360084,2019-01-22 19:10:11.397081,1,30.20.1.140,30.20.1.80,BYE,NaN,11,7
83,15954157787,8514560,2019-01-22 17:17:38.37884,NaN,2019-01-22 17:17:38.614088,0,30.20.1.12,30.20.1.7,486,busy here 这里忙,11,7
95,18353261700,8637024,2019-01-22 19:11:16.37402,NaN,2019-01-22 19:11:16.694708,0,30.20.1.140,30.20.1.136,487,request terminated 请求终止,11,7
120,13475769338,8576876,2019-01-22 19:12:04.495301,2019-01-22 19:12:39.237837,2019-01-22 19:12:39.285521,1,30.20.1.140,30.20.1.80,BYE,NaN,11,7
125,17553835258,8753747,2019-01-22 19:12:27.289919,2019-01-22 19:12:32.955393,2019-01-22 19:12:33.028887,1,30.20.1.12,30.20.1.80,BYE,NaN,11,7
136,18363992545,8842000,2019-01-22 19:12:20.005607,NaN,2019-01-22 19:13:17.951963,0,30.20.1.12,30.20.1.136,487,request terminated 请求终止,11,7
138,15550757070,8566326,2019-01-22 19:12:13.847534,2019-01-22 19:12:20.145373,2019-01-22 19:12:20.186044,1,30.20.1.140,30.20.1.80,BYE,NaN,11,7
144,17553835258,8753562,2019-01-22 19:13:52.696537,NaN,2019-01-22 19:14:25.894704,0,30.20.1.12,30.20.1.8,487,request terminated 请求终止,11,7
147,17563438990,8782775,2019-01-22 19:12:19.945698,NaN,2019-01-22 19:12:19.992398,0,30.20.1.12,30.20.1.6,404,not found 未发现,11,7
173,18553067101,8566326,2019-01-22 19:12:51.552777,NaN,2019-01-22 19:12:51.713055,0,30.20.1.140,30.20.1.80,486,busy here 这里忙,11,7
177,18553067101,8566326,2019-01-22 19:13:44.65051,2019-01-22 19:13:50.795749,2019-01-22 19:13:50.83866,1,30.20.1.140,30.20.1.80,BYE,NaN,11,7
...,...,...,...,...,...,...,...,...,...,...,...,...
91855,18753476111,8603230,2019-01-22 19:00:53.679548,NaN,2019-01-22 19:01:25.133053,0,30.20.1.12,30.20.1.8,487,request terminated 请求终止,11,7
91859,18854886935,8753912,2019-01-22 19:02:02.045468,2019-01-22 19:02:08.672082,2019-01-22 19:03:46.279106,99,30.20.1.12,30.20.1.8,BYE,NaN,11,7
91861,17305465545,8642896,2019-01-22 19:00:59.844913,2019-01-22 19:01:08.177496,2019-01-22 19:01:08.213216,1,30.20.1.140,30.20.1.208,BYE,NaN,11,7
91862,18905389521,8752313,2019-01-22 19:01:19.598425,2019-01-22 19:01:25.085558,2019-01-22 19:02:38.238905,74,30.20.1.12,30.20.1.80,BYE,NaN,11,7
91864,13225340071,8602222,2019-01-22 19:02:49.757563,NaN,2019-01-22 19:02:49.908261,0,30.20.1.12,30.20.1.80,486,busy here 这里忙,11,7
91866,18806343877,8782030,2019-01-22 19:00:43.993359,NaN,2019-01-22 19:00:52.755283,0,30.20.1.12,30.20.1.8,487,request terminated 请求终止,11,7
91878,13376360506,8638210,2019-01-23 00:05:29.60862,NaN,2019-01-23 00:05:45.286398,0,30.20.1.140,30.20.1.208,487,request terminated 请求终止,11,7
91890,13370830171,8843204,2019-01-23 00:05:16.543561,2019-01-23 00:05:27.604348,2019-01-23 00:05:27.592498,0,30.20.1.12,30.20.1.133,BYE,NaN,11,7
91895,17685847211,8845269,2019-01-23 00:05:41.888468,2019-01-23 00:05:48.592152,2019-01-23 00:05:48.605475,1,30.20.1.12,30.20.1.135,BYE,NaN,11,7
91902,18663458825,8783699,2019-01-23 00:22:52.278237,NaN,2019-01-23 00:23:49.754402,0,30.20.1.12,30.20.1.8,487,request terminated 请求终止,11,7
91909,18863337377,8465096,2019-01-23 00:22:47.355867,NaN,2019-01-23 00:22:47.514045,0,30.20.1.140,30.20.1.208,486,busy here 这里忙,11,7
91913,18863337377,8465096,2019-01-23 00:24:38.014233,2019-01-23 00:24:43.566978,2019-01-23 00:24:55.055842,1,30.20.1.140,30.20.1.208,487,request terminated 请求终止,11,7
91914,15853111955,8245659,2019-01-23 00:11:44.705919,NaN,2019-01-23 00:12:01.853539,0,30.20.1.12,30.20.1.136,487,request terminated 请求终止,11,7
91915,18663458825,8783699,2019-01-23 00:27:32.931103,NaN,2019-01-23 00:28:10.731588,0,30.20.1.12,30.20.1.8,487,request terminated 请求终止,11,7
91916,15853111955,8245589,2019-01-23 00:12:35.299712,2019-01-23 00:12:48.378021,2019-01-23 00:12:48.419387,1,30.20.1.12,30.20.1.80,BYE,NaN,11,7
91917,18663458825,8783699,2019-01-23 00:28:17.080412,NaN,2019-01-23 00:29:01.464466,0,30.20.1.12,30.20.1.8,487,request terminated 请求终止,11,7
91920,13964728313,8639333,2019-01-23 00:12:47.803574,2019-01-23 00:13:02.661511,2019-01-23 00:13:02.712505,1,30.20.1.140,30.20.1.80,BYE,NaN,11,7
91921,18663458825,8783699,2019-01-23 00:29:08.538049,NaN,2019-01-23 00:29:27.44763,0,30.20.1.12,30.20.1.8,487,request terminated 请求终止,11,7
91922,13954774889,8571384,2019-01-23 00:13:03.866235,2019-01-23 00:13:26.822128,2019-01-23 00:13:26.854954,1,30.20.1.140,30.20.1.208,BYE,NaN,11,7
91923,13626409678,8245599,2019-01-23 00:15:12.831324,2019-01-23 00:15:16.60585,2019-01-23 00:15:16.658943,1,30.20.1.12,30.20.1.80,BYE,NaN,11,7
91925,13589802377,8551328,2019-01-23 00:17:30.729827,NaN,2019-01-23 00:17:48.939373,0,30.20.1.140,30.20.1.136,487,request terminated 请求终止,11,7
91926,15689159687,8637666,2019-01-23 00:23:07.567772,2019-01-23 00:23:23.340633,2019-01-23 00:23:23.383238,1,30.20.1.140,30.20.1.208,BYE,NaN,11,7
91932,18663458825,8783699,2019-01-23 00:29:40.040135,NaN,2019-01-23 00:30:38.152622,0,30.20.1.12,30.20.1.8,487,request terminated 请求终止,11,7
91934,18663458825,8783699,2019-01-23 00:23:55.123288,NaN,2019-01-23 00:24:36.869628,0,30.20.1.12,30.20.1.8,487,request terminated 请求终止,11,7
91935,18863337377,8465096,2019-01-23 00:22:52.663322,2019-01-23 00:22:58.165043,2019-01-23 00:22:58.175559,1,30.20.1.140,30.20.1.135,BYE,NaN,11,7
91936,18663458825,8783699,2019-01-23 00:26:01.283508,NaN,2019-01-23 00:26:48.709904,0,30.20.1.12,30.20.1.8,487,request terminated 请求终止,11,7
91938,18863337377,8465096,2019-01-23 00:20:06.058109,2019-01-23 00:20:11.970294,2019-01-23 00:20:12.006586,1,30.20.1.140,30.20.1.208,BYE,NaN,11,7
91944,18663458825,8783699,2019-01-23 00:24:42.308929,NaN,2019-01-23 00:25:30.434861,0,30.20.1.12,30.20.1.8,487,request terminated 请求终止,11,7
91945,18663458825,8783699,2019-01-23 00:26:54.590629,NaN,2019-01-23 00:27:27.727918,0,30.20.1.12,30.20.1.8,487,request terminated 请求终止,11,7
91946,18863337377,8465096,2019-01-23 00:22:13.166904,NaN,2019-01-23 00:22:13.269833,0,30.20.1.140,30.20.1.135,486,busy here 这里忙,11,7

## 4.功能一：通话原始数据可视化

## 5.功能二：呼叫流向和流量可视化

## 6.功能三：周期内呼叫量变化分析

## 7.功能四：基于人工智能/机器学习的话务量、流向预测（人工智能模型设计与分析）

## 8.功能五：IMS网络关键节点负载比/吞吐量监控